server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

logging:
  file:
    name: logs/construction-materials-prod.log
  level:
    root: WARN
    org.example.constructionmaterialsapi: INFO


management:
  endpoints:
    web:
      exposure:
        include: health, info